### PR TITLE
Create l10n_it.xml

### PR DESCRIPTION
**Pull request by Rudolfet**
Creation translation on italian

### CODE REVIEW

**Review by GMNGjoy — APPROVED** [review]
Looks great, thank you for contributing!

**Comment by GMNGjoy** [comment]
@Rudolfet Follow-up - all the UI settings are now in game, which require quite a few more translated strings!

see https://github.com/GMNGjoy/FS25_ContractBoost/issues/26 for more information. 

Any help is appreciated!

**Comment by FirenzeIT** [comment]
Hi @GMNGjoy, i translate all in Italian's language, so you can add them on your mod in official's way 👍🏻 Please check up and verify syntax for avoid eventually errors. Also because my game (in ITA language) it's all missing l10n etc...

[l10n_it.txt](https://github.com/user-attachments/files/18167398/l10n_it.txt)

**Comment by Rudolfet** [comment]
Sorry for the delay. Thanks a lot @FirenzeIT for the help.

**Pull request merged**
